### ISSUE TITLE
Not issue

### ISSUE THREAD

**Issue by arcaela** [kanryu/puremongo#1]
This is the best open source library I could get my hands on, I have been writing a library similar to "Laravel Eloquent" for a long time at github.com/arcaelas/arcaelas/ 

The thing is that I still haven't been able to understand how you created the logical comparators like $eq,$not and others inside the query... I'm still seeing the code but I would like to understand it better.

Tienes mi respeto.
You have my respect.

**Comment by arcaela** [comment]
I will close this ticket, because I already know that you have read.

Greetings.

**Comment by kanryu** [comment]
Thanks for finding my implementation!

My implementation implements some comparison operators, but not all. Please run Unit Tests to check the operation. :)
